### ISSUE TITLE
Adding public methods from handlers

### ISSUE THREAD

**Issue by james-shaw-turner** [dchambers/composerjs#27]
@dchambers 

Imagine a handler responsible for executing trades on a server based on data in the model. If I were writing a GUI I would like to write the following code:

``` JavaScript
function onBuyButtonClicked(){
   this.trade.execute("buy");
}
```

I want to write a TradeExecutionHandler with an execute method that is exported onto the model object. My assumption is I would have to write something like as shown below

``` JavaScript
function Trade() {
  composerjs.mixinTo(this);
  var tradeHandler = new TradeHandler();
  this.addHandler(tradeHandler);
  this.execute = tradeHandler.execute.bind(this);
  this.seal();
}
```

**Comment by dchambers** [comment]
Yes, that's exactly right.

I suspect this is a good thing as it allows the developer to explicitly control the methods that are exposed on their public API. Additionally, although you might think that this could become arduous as the number of handler methods that would need to be mapped increases, I've so far noticed that when converting handlers from CM to CJS I end up getting rid of the handler methods because they make the handler code more complicated.

Now, to be clear, I'm not getting rid of these methods because CJS doesn't have a mechanism for automatically exposing handler methods, since it would be trivial to add such a mechanism. Instead, I'm getting rid of them because often in CJS these methods turn out to be an _anti-patterns_ that can be better modelled using input-properties (if you look at the example code so far you'll see examples of this).

Now, I haven't yet encountered enough CM handler methods to have a definitive list of conversion patterns, but at this point I suspect the following:
1. Methods that involve switching (e.g. `pause()` and `resume()`) are better modelled using a single boolean _input-property_ flag.
2. Methods that receive arguments may be better modelled using _input-properties_ for those argument(s), allowing `set()` to be used for any changes.

A further side benefit of using properties is that the handlers become even more composable! Of course, as I encounter more handlers, and have exposure to more use-cases, my views might change as to the need for a _handler-method_ export mechanism, but at present I think I've got it right.

**Comment by james-shaw-turner** [comment]
@dchambers
I'm happy with that - we have a (not too onerous) mechanism that means we can satisfy the requirement but don't encourage export of methods.  We just need an example to show how it is expected to be done.
