### ISSUE TITLE
The stringify() method should conform to the JSON.stringify() API

### ISSUE THREAD

**Issue by bit-shifter** [dchambers/composerjs#4]
If we are going to adopt method names from existing APIs we should make sure that the source API is adhered to.

Likewise, if we are going to use #stringify, we should use the #parse in preference to #unstringify.

**Comment by dchambers** [comment]
I used `stringify()` because @james-shaw-turner used it, but I didn't use `parse()` because it didn't feel right for a deserializing operation. Maybe we shouldn't use `stringify()` either?

**Comment by dchambers** [comment]
@james-shaw-turner / @janhancic / @adamshone: do any of you have an opinion on this?

**Comment by dchambers** [comment]
Given that nobody else expressed an opinion I'm closing as I've now made the suggested change.

**Comment by dchambers** [comment]
Re-opening as @bit-shifter has explained to me that I hadn't fully understood the point he was making. Additionally, on reflection, I don't think it makes sense that we are serializing to a string anyway, since a JSON object would be more useful, and `JSON.stringify()` could then be used if a string really is required.
